{
    'name': 'Bulk Material Dispatch',
    'version': '19.0.1.1.2',
    'summary': 'Batch, dispatch, deliver and invoice concrete, asphalt, precast and other '
               'bulk-batched construction materials, m³ by m³.',
    'license': 'LGPL-3',
    'category': 'Manufacturing/Concrete & Bulk Material Dispatch',
    'author': 'aKross Information Technology (sales@akross.ae)',
    'website': 'https://akross.ae',
    'support': 'sales@akross.ae',
    'depends': [
        'base', 'mail', 'product', 'uom',
        'sale_management', 'project', 'stock', 'mrp',
        'fleet', 'account',
    ],
    'data': [
        'security/rmc_security_groups.xml',
        'security/rmc_security_rules.xml',
        'security/ir.model.access.csv',
        'data/rmc_uom_data.xml',
        'data/rmc_sequence_data.xml',
        'data/rmc_return_reason_data.xml',
        'wizard/rmc_credit_override_wizard_views.xml',
        'views/rmc_load_views.xml',
        'views/rmc_project_rate_views.xml',
        'views/rmc_calloff_views.xml',
        'views/rmc_qc_sample_views.xml',
        'views/rmc_return_reason_views.xml',
        'views/product_template_views.xml',
        'views/mrp_bom_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_views.xml',
        'report/rmc_delivery_ticket_report.xml',
        'report/rmc_daily_dispatch_report_views.xml',
        'report/rmc_load_margin_report_views.xml',
        'report/rmc_cement_variance_report_views.xml',
        'views/rmc_menus.xml',
    ],
    'demo': [
        'demo/rmc_demo_data.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
}
