from . import rmc_return_reason
from . import rmc_project_rate
from . import rmc_calloff
from . import rmc_load
from . import rmc_qc_sample
from . import product_template
from . import mrp_bom
from . import fleet_vehicle
from . import sale_order_line
from . import account_move_line
from . import res_company
from . import res_config_settings
from . import rmc_load_margin_report
from . import rmc_cement_variance_report
